version: "3.2"
services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_banking
      PGDATA: var/lib/postgresql/data/pg/data
    restart: unless-stopped